name: print_script
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path:
  google_fonts:
  dotted_border:
  dropdown_button2: ^2.3.9
  file_saver: ^0.2.14
  path_provider:
  autotrie: ^2.0.0
  characters: ^1.2.1
  charcode: ^1.3.1
  collection: ^1.17.2
  equatable: ^2.0.5
  http: ^1.1.0

  linked_scroll_controller: ^0.2.0
  meta: ^1.9.1
  mocktail: ^1.0.1
  scrollable_positioned_list: ^0.3.5
  tuple: ^2.0.1
  url_launcher: ^6.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  fake_async: ^1.3.1
  test: ^1.16.5
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

